name: app
description: A new Flutter project.
publish_to: none
version: 1.0.0+1
environment:
  sdk: ">=3.0.5 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.5
  intl: ^0.18.1
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  get_storage: ^2.1.1
  url_launcher: ^6.3.2
  flutter_native_splash: ^2.4.4
  smooth_page_indicator: ^1.2.1
  provider: ^6.1.5
  carousel_slider: ^5.1.1
  readmore: ^3.0.0
  flutter_rating_bar: ^4.0.1


  connectivity_plus: ^5.0.1
  lottie: ^3.0.0

  convert: ^3.1.2
 
  ## -- FIREBASE PACKAGES
  firebase_auth: ^5.5.3
  firebase_core: ^3.13.0
  google_sign_in: ^6.3.0
  cloud_firestore: ^5.6.7
  firebase_storage: ^12.4.5
  firebase_messaging: ^15.2.6
  firebase_crashlytics: ^4.3.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  #--------------- LOCAL ASSETS ------------------#
  assets:
    - assets/logo/
    - assets/images/
    - assets/icons/brands/
    - assets/images/profile/
    - assets/images/dashboard/
    - assets/images/splash_images/
    - assets/images/welcome_images/
    - assets/images/forget_password/
    - assets/images/on_boarding_images/
    - assets/images/animations/
    - assets/images/banners/
    - assets/icons/payment_methods/
    - assets/images/products/
    - assets/images/brands/
    - assets/icons/categories/
    - assets/icons/payment_methods/paypal.png
  #--------------- LOCAL FONTS ------------------#
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800
