// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOQOJsV8l1mdMVxu1Dvx7VNEatSOyw9wM',
    appId: '1:887237639434:web:abdfb9218390e5b1608ef3',
    messagingSenderId: '887237639434',
    projectId: 'demoflutter-58e88',
    authDomain: 'demoflutter-58e88.firebaseapp.com',
    storageBucket: 'demoflutter-58e88.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxLiFM839CfD-ggfjoby3jPoiiOE96f88',
    appId: '1:887237639434:android:a100222a161a3832608ef3',
    messagingSenderId: '887237639434',
    projectId: 'demoflutter-58e88',
    storageBucket: 'demoflutter-58e88.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1UK3ejr6z36ZGZaBvjlRt8NT5Mln91-s',
    appId: '1:887237639434:ios:6d0ef3d931724269608ef3',
    messagingSenderId: '887237639434',
    projectId: 'demoflutter-58e88',
    storageBucket: 'demoflutter-58e88.firebasestorage.app',
    androidClientId: '887237639434-h7sqnlk8lg6mfgdd4jgmgmmstdk77gnn.apps.googleusercontent.com',
    iosClientId: '887237639434-qci5ng37fe4tirhlidf9jnj9r2u00s08.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1UK3ejr6z36ZGZaBvjlRt8NT5Mln91-s',
    appId: '1:887237639434:ios:6d0ef3d931724269608ef3',
    messagingSenderId: '887237639434',
    projectId: 'demoflutter-58e88',
    storageBucket: 'demoflutter-58e88.firebasestorage.app',
    androidClientId: '887237639434-h7sqnlk8lg6mfgdd4jgmgmmstdk77gnn.apps.googleusercontent.com',
    iosClientId: '887237639434-qci5ng37fe4tirhlidf9jnj9r2u00s08.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCOQOJsV8l1mdMVxu1Dvx7VNEatSOyw9wM',
    appId: '1:887237639434:web:4f13a5d1ddbbf335608ef3',
    messagingSenderId: '887237639434',
    projectId: 'demoflutter-58e88',
    authDomain: 'demoflutter-58e88.firebaseapp.com',
    storageBucket: 'demoflutter-58e88.firebasestorage.app',
  );

}