// // File generated by FlutterFire CLI.
// // ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;

// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         return macos;
//       case TargetPlatform.windows:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for windows - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }

//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyCMqE0Uim5kS3pWUdeNTHzyQMVwc5TSxf8',
//     appId: '1:93011819765:web:b2993c6add1b1255bc19bc',
//     messagingSenderId: '93011819765',
//     projectId: 'phamarciapp-498a0',
//     authDomain: 'phamarciapp-498a0.firebaseapp.com',
//     storageBucket: 'phamarciapp-498a0.appspot.com',
//     measurementId: 'G-D89B8TGVX1',
//   );

//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyAyWqN0vUuiAk0ht2TUIKSpZjUdeEkMg-8',
//     appId: '1:93011819765:android:133aa1de7e470eddbc19bc',
//     messagingSenderId: '93011819765',
//     projectId: 'phamarciapp-498a0',
//     storageBucket: 'phamarciapp-498a0.appspot.com',
//   );

//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyCQyG3MruWBMxkxIpkti3TQW3Vgb3kd8m0',
//     appId: '1:93011819765:ios:f1b04f6117df6bafbc19bc',
//     messagingSenderId: '93011819765',
//     projectId: 'phamarciapp-498a0',
//     storageBucket: 'phamarciapp-498a0.appspot.com',
//     iosClientId: '93011819765-7invve8elrhp6i7mf9u1blb98e8nqa1g.apps.googleusercontent.com',
//     iosBundleId: 'com.example.appMobiPharmacy',
//   );

//   static const FirebaseOptions macos = FirebaseOptions(
//     apiKey: 'AIzaSyCQyG3MruWBMxkxIpkti3TQW3Vgb3kd8m0',
//     appId: '1:93011819765:ios:394f08b6d8b382f8bc19bc',
//     messagingSenderId: '93011819765',
//     projectId: 'phamarciapp-498a0',
//     storageBucket: 'phamarciapp-498a0.appspot.com',
//     iosClientId: '93011819765-2qjkvj3kt4csshgjqvkhllah3p5stchc.apps.googleusercontent.com',
//     iosBundleId: 'com.example.appMobiPharmacy.RunnerTests',
//   );
// }
